"""Pipeline hooks — integrates OraClaw intelligence into DeckForge pipelines.

These hooks are called at key points in the render and content pipelines
to inject intelligent decision-making. All hooks are no-ops when OraClaw
is disabled, ensuring DeckForge works standalone.
"""

from __future__ import annotations

import logging
from typing import Any

from deckforge.intelligence.client import get_oraclaw

logger = logging.getLogger(__name__)


async def select_intelligent_theme(
    user_theme: str,
    metadata: dict[str, Any] | None = None,
) -> str:
    """Select the best theme using OraClaw bandit, or return user's choice.

    Called before the render pipeline resolves the theme. If OraClaw is
    enabled and the user hasn't explicitly specified a theme (or specified
    "auto"), the bandit selects the optimal theme based on presentation context.

    Args:
        user_theme: The theme ID from the user's request.
        metadata: Optional presentation metadata (purpose, audience).

    Returns:
        Theme ID to use for rendering.
    """
    if user_theme != "auto":
        return user_theme

    client = get_oraclaw()
    if client is None:
        return "corporate-blue"

    from deckforge.intelligence.theme_selector import BanditThemeSelector

    selector = BanditThemeSelector()
    audience = (metadata or {}).get("audience", "general")
    purpose = (metadata or {}).get("purpose", "report")

    selected = await selector.select(
        audience=audience,
        purpose=purpose,
        user_theme=user_theme if user_theme != "auto" else None,
    )
    logger.info("Intelligence: selected theme '%s' for %s/%s", selected, audience, purpose)
    return selected


async def qa_with_convergence(
    qa_report: Any,
    presentation: Any,
) -> Any:
    """Enhance QA report with multi-LLM convergence scoring.

    Called after the standard QA pipeline runs. Adds convergence metrics
    if OraClaw is available and the presentation was generated by AI
    (not rendered from user-provided IR).

    Args:
        qa_report: Standard QA report from QAPipeline.
        presentation: The Presentation IR model.

    Returns:
        Enhanced QA report with convergence data, or original report.
    """
    client = get_oraclaw()
    if client is None:
        return qa_report

    # Only run convergence scoring on AI-generated content
    gen_meta = getattr(presentation, "metadata", None)
    if gen_meta is None:
        return qa_report

    from deckforge.intelligence.content_qa import ConvergenceQA

    cqa = ConvergenceQA()

    # Score overall presentation quality as "convergence" between
    # the QA pipeline's subscores
    scores = {
        "contrast": qa_report.contrast_score if hasattr(qa_report, "contrast_score") else 0.8,
        "overflow": qa_report.overflow_score if hasattr(qa_report, "overflow_score") else 0.8,
        "alignment": qa_report.alignment_score if hasattr(qa_report, "alignment_score") else 0.8,
        "readability": qa_report.score,
    }

    convergence = await cqa.score_content(scores)
    if convergence:
        qa_report.intelligence = {
            "convergence_score": convergence["convergence_score"],
            "recommendation": convergence["recommendation"],
            "powered_by": "oraclaw",
        }
        logger.info(
            "Intelligence QA: convergence=%.3f, recommendation=%s",
            convergence["convergence_score"],
            convergence["recommendation"],
        )

    return qa_report


async def enrich_finance_slide(
    slide_type: str,
    elements: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Enrich finance slide elements with Monte Carlo projections.

    Called during content generation for finance-specific slide types.
    Adds realistic scenario data powered by OraClaw's Monte Carlo engine.

    Args:
        slide_type: The finance slide type (e.g., "dcf_summary", "returns_analysis").
        elements: Current slide elements.

    Returns:
        Enhanced elements with Monte Carlo data, or original elements.
    """
    client = get_oraclaw()
    if client is None:
        return elements

    from deckforge.intelligence.finance_projections import MonteCarloProjections

    mc = MonteCarloProjections()

    if slide_type == "dcf_summary":
        result = await mc.dcf_scenarios(
            base_revenue=10_000_000,
            growth_mean=0.12,
            growth_std=0.06,
        )
        if result:
            elements.append({
                "type": "footnote",
                "content": (
                    f"Scenarios: Bear ${result['projections']['bear_case']:,.0f} | "
                    f"Base ${result['projections']['base_case']:,.0f} | "
                    f"Bull ${result['projections']['bull_case']:,.0f} "
                    f"({result['simulations']:,} simulations, OraClaw Monte Carlo)"
                ),
            })

    elif slide_type == "returns_analysis":
        result = await mc.returns_waterfall(
            entry_value=100_000_000,
            irr_mean=0.20,
            irr_std=0.08,
        )
        if result:
            scenarios = result["scenarios"]
            elements.append({
                "type": "footnote",
                "content": (
                    f"Returns: Downside {scenarios['downside']['moic']:.1f}x / "
                    f"Base {scenarios['base']['moic']:.1f}x / "
                    f"Upside {scenarios['upside']['moic']:.1f}x "
                    f"({result['simulations']:,} simulations, OraClaw Monte Carlo)"
                ),
            })

    elif slide_type == "sensitivity_table":
        result = await mc.sensitivity_matrix(
            base_value=100_000_000,
            row_variable="Revenue Growth",
            col_variable="WACC",
        )
        if result:
            # Attach sensitivity data as metadata for the renderer
            for elem in elements:
                if elem.get("type") == "table":
                    elem["_sensitivity_matrix"] = result

    return elements


def is_intelligence_enabled() -> bool:
    """Check if the intelligence layer is available."""
    return get_oraclaw() is not None
