"""Provision a dedicated `deckforge` schema inside the existing Supabase Postgres.

Reads creds from ~/.claude/secrets/modelforge-deploy.env, never prints them.
Idempotent: re-runnable.

After this runs, the connection string for deckforge becomes:
    postgresql://postgres:<password>@db.<project-ref>.supabase.co:5432/postgres?options=-csearch_path%3Ddeckforge

That URL is what you paste into Render's DECKFORGE_DATABASE_URL env var.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from urllib.parse import urlparse

import psycopg

VAULT = Path.home() / ".claude" / "secrets" / "modelforge-deploy.env"


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    for line in VAULT.read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def main() -> int:
    env = load_env()
    supabase_url = env["SUPABASE_URL"]
    db_password = env["SUPABASE_DB_PASSWORD"]
    project_ref = urlparse(supabase_url).hostname.split(".")[0]

    # Supabase deprecated direct host on free tier — must use regional pooler.
    # Project region is unknown to us; brute-force common AWS regions in priority order.
    candidates = [
        "eu-central-1", "eu-west-1", "us-east-1", "us-west-1",
        "ap-southeast-1", "ap-south-1", "ap-northeast-1", "sa-east-1",
    ]
    conn_str_admin = None
    region = None
    for region in candidates:
        host = f"aws-0-{region}.pooler.supabase.com"
        # Session pooler uses port 5432 with user `postgres.<ref>` for direct-mode features (DDL).
        candidate = (
            f"postgresql://postgres.{project_ref}:{db_password}@{host}:5432/postgres"
        )
        try:
            with psycopg.connect(candidate, connect_timeout=8) as c:
                with c.cursor() as cur:
                    cur.execute("SELECT 1")
            conn_str_admin = candidate
            print(f"[setup] region detected: {region}")
            break
        except Exception as e:
            print(f"[setup] {region}: not this one ({type(e).__name__})")
            continue
    if conn_str_admin is None:
        print("[setup] FAILED: could not find Supabase project region in any candidate.", file=sys.stderr)
        return 2

    print(f"[setup] connecting to aws-0-{region}.pooler.supabase.com (admin user, default schema)...")
    try:
        with psycopg.connect(conn_str_admin, connect_timeout=15) as conn:
            with conn.cursor() as cur:
                cur.execute("CREATE SCHEMA IF NOT EXISTS deckforge;")
                cur.execute("SELECT current_database(), current_user, version();")
                row = cur.fetchone()
                print(f"[setup] connected: db={row[0]} user={row[1]}")
                cur.execute(
                    """
                    SELECT schema_name FROM information_schema.schemata
                    WHERE schema_name = 'deckforge';
                    """
                )
                if cur.fetchone():
                    print("[setup] schema 'deckforge' exists ✓")
                conn.commit()
    except Exception as exc:
        print(f"[setup] FAILED: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1

    pooler_host = f"aws-0-{region}.pooler.supabase.com"
    deckforge_url = (
        f"postgresql://postgres.{project_ref}:{db_password}@{pooler_host}:5432/postgres"
        f"?options=-csearch_path%3Ddeckforge,public"
    )
    # Write the URL to a local file with restrictive name so the user can copy it
    out = Path.home() / ".claude" / "secrets" / "deckforge.env"
    out.write_text(
        f"# Deckforge — Supabase Postgres (deckforge schema in shared modelforge project)\n"
        f"# Generated by SlideMaker/scripts/setup_deckforge_db.py\n"
        f"DECKFORGE_DATABASE_URL={deckforge_url}\n"
        f"# Same project as modelforge — see modelforge-deploy.env for SUPABASE_URL/keys.\n"
    )
    print(f"[setup] wrote DECKFORGE_DATABASE_URL to {out}")
    print("[setup] next: run alembic upgrade head against this URL (script: run_alembic.py)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
